package com.mds.decisionsupport;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "test")
public class Test  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Item name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String itemName;
    
    @org.kie.api.definition.type.Key
    @org.kie.api.definition.type.Label(value = "Responce")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String responce;

    public Test() {
    }

    public Test(java.lang.String itemName, java.lang.String responce) {
        this.itemName = itemName;
        this.responce = responce;
    }


    
    public java.lang.String getItemName() {
        return this.itemName;
    }

    public void setItemName(  java.lang.String itemName ) {
        this.itemName = itemName;
    }
    
    public java.lang.String getResponce() {
        return this.responce;
    }

    public void setResponce(  java.lang.String responce ) {
        this.responce = responce;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        com.mds.decisionsupport.Test that = (com.mds.decisionsupport.Test)o;
        if (itemName != null ? !itemName.equals(that.itemName) : that.itemName != null) return false;
        if (responce != null ? !responce.equals(that.responce) : that.responce != null) return false;
        return true;
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 13 * result + (itemName != null ? itemName.hashCode() : 0);
        result = 13 * result + (responce != null ? responce.hashCode() : 0);
        return result;
    }
}