package com.mds.factmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Amount")
public class Amount  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "unite")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String unite;
    
    @org.kie.api.definition.type.Label(value = "valeur")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String valeur;
    
    @org.kie.api.definition.type.Label(value = "localName")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String localName;

    public Amount() {
    }

    public Amount(java.lang.String unite, java.lang.String valeur, java.lang.String localName) {
        this.unite = unite;
        this.valeur = valeur;
        this.localName = localName;
    }


    
    public java.lang.String getUnite() {
        return this.unite;
    }

    public void setUnite(  java.lang.String unite ) {
        this.unite = unite;
    }
    
    public java.lang.String getValeur() {
        return this.valeur;
    }

    public void setValeur(  java.lang.String valeur ) {
        this.valeur = valeur;
    }
    
    public java.lang.String getLocalName() {
        return this.localName;
    }

    public void setLocalName(  java.lang.String localName ) {
        this.localName = localName;
    }




}