package com.mds.factmodel;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Fiche Patient")
public class FichePatient  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String hasAdministrativeGenderCode;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.Date hasBirthDate;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String hasEmail;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String hasFirstName;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String hasLastName;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String hasPhoneNumber;
    
    @org.kie.api.definition.type.Label(value = "symptomesPatient")
    @org.kie.api.definition.type.Position(value = 6)
    private java.util.List<com.mds.factmodel.Symptome> symptomesPatient;

    public FichePatient() {
    }

    public FichePatient(java.lang.String hasAdministrativeGenderCode, java.lang.String hasFirstName, java.lang.String hasLastName, java.util.Date hasBirthDate, java.lang.String hasEmail, java.lang.String hasPhoneNumber, java.util.List<com.mds.factmodel.Symptome> symptomesPatient) {
        this.hasAdministrativeGenderCode = hasAdministrativeGenderCode;
        this.hasFirstName = hasFirstName;
        this.hasLastName = hasLastName;
        this.hasBirthDate = hasBirthDate;
        this.hasEmail = hasEmail;
        this.hasPhoneNumber = hasPhoneNumber;
        this.symptomesPatient = symptomesPatient;
    }


    
    public java.lang.String getHasAdministrativeGenderCode() {
        return this.hasAdministrativeGenderCode;
    }

    public void setHasAdministrativeGenderCode(  java.lang.String hasAdministrativeGenderCode ) {
        this.hasAdministrativeGenderCode = hasAdministrativeGenderCode;
    }
    
    public java.util.Date getHasBirthDate() {
        return this.hasBirthDate;
    }

    public void setHasBirthDate(  java.util.Date hasBirthDate ) {
        this.hasBirthDate = hasBirthDate;
    }
    
    public java.lang.String getHasEmail() {
        return this.hasEmail;
    }

    public void setHasEmail(  java.lang.String hasEmail ) {
        this.hasEmail = hasEmail;
    }
    
    public java.lang.String getHasFirstName() {
        return this.hasFirstName;
    }

    public void setHasFirstName(  java.lang.String hasFirstName ) {
        this.hasFirstName = hasFirstName;
    }
    
    public java.lang.String getHasLastName() {
        return this.hasLastName;
    }

    public void setHasLastName(  java.lang.String hasLastName ) {
        this.hasLastName = hasLastName;
    }
    
    public java.lang.String getHasPhoneNumber() {
        return this.hasPhoneNumber;
    }

    public void setHasPhoneNumber(  java.lang.String hasPhoneNumber ) {
        this.hasPhoneNumber = hasPhoneNumber;
    }
    
    public java.util.List<com.mds.factmodel.Symptome> getSymptomesPatient() {
        return this.symptomesPatient;
    }

    public void setSymptomesPatient(  java.util.List<com.mds.factmodel.Symptome> symptomesPatient ) {
        this.symptomesPatient = symptomesPatient;
    }
}